version: '3'

services:
    app:
      build: .
      ports:
        - "80:80"
      volumes:
        - ./app:/var/www/html
      links:
        - db
    db:
        image: mysql:5.5
        command: --init-file /var/lib/mysql/db.sql
        volumes:
          - ./dump/db.sql:/var/lib/mysql/db.sql
        ports:
            - "3307:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
#    myadmin:
#        image: phpmyadmin/phpmyadmin
#        ports:
#            - "8080:80"
#        links:
#            - db:db
